---
- name: Create User
  user:
    comment: Prometheus Node Exporter User
    name: "{{ pne_user_id }}"
    createhome: no
    shell: /bin/false
  group:
    state: present
    name: "{{ pne_user_gid }}"